stages:
  - build
  - deploy


variables:
  VERSION:
    value: develop
    description: Package version

build:
  stage: build

  script:
    - docker build .

  tags:
    - linux-containers
    - docker

deploy:

  rules:
    - if: $CI_PIPELINE_SOURCE != "web" && $CI_PIPELINE_SOURCE != "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH =~ /^release\/[\s\S]+$/ || $CI_COMMIT_BRANCH == "main"
      variables:
        TAG: production
        NODE_ENV: production
    - if: $CI_COMMIT_BRANCH != "main" && '$CI_COMMIT_BRANCH !=~ /^release\/[\s\S]+$/'
      variables:
        TAG: develop
        NODE_ENV: development

  stage: deploy

  dependencies:
    - build

  before_script:
    - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 723178373366.dkr.ecr.eu-central-1.amazonaws.com

  script:
    - docker build --target backend -t corecount/backend:$VERSION --build-arg VERSION=$VERSION --build-arg NODE_ENV=$NODE_ENV --build-arg SENTRY=$SENTRY_AUTH_TOKEN .
    - docker tag corecount/backend:$VERSION 723178373366.dkr.ecr.eu-central-1.amazonaws.com/corecount/backend:$VERSION
    - docker push 723178373366.dkr.ecr.eu-central-1.amazonaws.com/corecount/backend:$VERSION

    - docker build --target dashboard -t corecount/dashboard:$VERSION --build-arg NODE_ENV=$NODE_ENV --build-arg VERSION=$VERSION .
    - docker tag corecount/dashboard:$VERSION 723178373366.dkr.ecr.eu-central-1.amazonaws.com/corecount/dashboard:$VERSION
    - docker push 723178373366.dkr.ecr.eu-central-1.amazonaws.com/corecount/dashboard:$VERSION

  tags:
    - linux-containers
    - docker